name: mobifone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^7.0.0
  path_provider: ^2.0.10
  keyboard_dismisser: ^2.0.0
  image_picker: ^0.8.5+3
  community_material_icon: ^5.9.55
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  formz: ^0.4.1
  equatable: ^2.0.3
  intl: ^0.17.0
  toggle_switch: ^1.3.0
  font_awesome_flutter: ^9.2.0
  double_back_to_close_app: ^2.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.17
  bubble_tab_indicator: ^0.1.6
  change_app_package_name: ^1.0.0
  titled_navigation_bar: ^4.1.0
  card_swiper: ^1.0.4
  page_indicator: ^0.4.1
  smooth_page_indicator: ^1.0.0+2
  dropdown_below: ^1.0.3
  flutter_mobx: ^2.0.3+2
  nb_utils: ^4.4.10
  get: ^4.6.1
  pin_code_fields: ^7.3.0
  android_intent: ^2.0.2
  get_it: ^7.2.0
  logger: ^1.1.0
  flash: ^2.0.3+1
  dio: ^4.0.4
  lottie: ^1.2.1
  shared_preferences: ^2.0.11
  json_annotation: ^4.4.0
  retrofit: ^3.0.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  retrofit_generator: ^3.0.1+1
  http: ^0.13.4
  meta: ^1.7.0
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  grouped_list: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans/NunitoSans-Italic.ttf
          style: italic

  assets:
    - .env
    - assets/lottie/
    - assets/images/
    - assets/fonts/
    - assets/icons/
